name: External Switches Plugin
main: info.johndalton.bukkit.externalswitches.ExternalSwitchesPlugin
version: 0.1
commands:
  switchtoggle:
    description: Toggles a lever at the given coordinates.
    usage: /switchtoggle x y z
